//Aluno: Claudiney Júnoior Givisiez Thomáz R.A.: 2266326

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author claud
 */
public class CadBlended extends javax.swing.JFrame {

    private Blended blend;
    private GerWhiskeys gerWhis = new GerWhiskeys();
    
    private static CadBlended cadBlendUnic;
    /**
     * Creates new form CadWhiskey
     */
    private CadBlended() {
        initComponents();
    }
    
    public static CadBlended getCadBlend(){
        if(cadBlendUnic == null){
            cadBlendUnic = new CadBlended();
        }
        return cadBlendUnic;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rtCodigo = new javax.swing.JLabel();
        cxCodigo = new javax.swing.JTextField();
        rtMarca = new javax.swing.JLabel();
        cxMarca = new javax.swing.JTextField();
        rtOrigem = new javax.swing.JLabel();
        cxOrigem = new javax.swing.JTextField();
        rtTeor = new javax.swing.JLabel();
        cxTeor = new javax.swing.JTextField();
        rtPreco = new javax.swing.JLabel();
        cxPreco = new javax.swing.JTextField();
        rtCereais = new javax.swing.JLabel();
        cxCereais = new javax.swing.JTextField();
        btCadastrar = new javax.swing.JButton();
        btLimpar = new javax.swing.JButton();
        btSair = new javax.swing.JButton();
        rtTitulo = new javax.swing.JLabel();
        rtCereais1 = new javax.swing.JLabel();
        btMalte = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblBlend = new javax.swing.JTable();
        btAltCadastro1 = new javax.swing.JButton();
        rtCodAlt = new javax.swing.JLabel();
        cxCodigoAlt = new javax.swing.JTextField();
        rtCodDel = new javax.swing.JLabel();
        cxCodigoDel = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        rtCodigo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        rtCodigo.setText("Codigo:");

        cxCodigo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cxCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cxCodigoActionPerformed(evt);
            }
        });

        rtMarca.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        rtMarca.setText("Marca:");

        cxMarca.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cxMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cxMarcaActionPerformed(evt);
            }
        });

        rtOrigem.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        rtOrigem.setText("Origem:");

        cxOrigem.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cxOrigem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cxOrigemActionPerformed(evt);
            }
        });

        rtTeor.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        rtTeor.setText("Teor:");

        cxTeor.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cxTeor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cxTeorActionPerformed(evt);
            }
        });

        rtPreco.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        rtPreco.setText("Preco:");

        cxPreco.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cxPreco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cxPrecoActionPerformed(evt);
            }
        });

        rtCereais.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        rtCereais.setText("Graos:");

        cxCereais.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cxCereais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cxCereaisActionPerformed(evt);
            }
        });

        btCadastrar.setText("Cadastrar");
        btCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCadastrarActionPerformed(evt);
            }
        });

        btLimpar.setText("Limpar");
        btLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimparActionPerformed(evt);
            }
        });

        btSair.setText("Sair");
        btSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSairActionPerformed(evt);
            }
        });

        rtTitulo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        rtTitulo.setText("Cadastrar Blended");

        rtCereais1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        rtCereais1.setText("Malte:");

        btMalte.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btMalte.setText("Maltado");
        btMalte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMalteActionPerformed(evt);
            }
        });

        tblBlend.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Codigo", "Marca", "Origem", "Teor", "Preco", "Graos", "Malte"
            }
        ));
        jScrollPane1.setViewportView(tblBlend);

        btAltCadastro1.setText("Alterar Preco");
        btAltCadastro1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAltCadastro1ActionPerformed(evt);
            }
        });

        rtCodAlt.setText("Codigo para alterar:");

        rtCodDel.setText("Codigo para deletar:");

        jButton1.setText("Excluir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rtCodigo)
                            .addComponent(rtMarca)
                            .addComponent(rtTeor)
                            .addComponent(rtPreco)
                            .addComponent(rtCereais)
                            .addComponent(rtCereais1)
                            .addComponent(rtOrigem))
                        .addGap(120, 120, 120)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(cxPreco)
                                    .addComponent(cxTeor)
                                    .addComponent(cxOrigem)
                                    .addComponent(cxMarca, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cxCereais)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(btMalte)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(cxCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(20, 20, 20))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btCadastrar)
                                .addGap(18, 18, 18)
                                .addComponent(btLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btSair, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(20, 20, 20))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addComponent(rtTitulo)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rtCodDel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cxCodigoDel, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rtCodAlt)
                                .addGap(12, 12, 12)
                                .addComponent(cxCodigoAlt, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btAltCadastro1)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rtTitulo)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rtCodigo)
                    .addComponent(cxCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rtMarca)
                    .addComponent(cxMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rtOrigem)
                    .addComponent(cxOrigem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rtTeor)
                    .addComponent(cxTeor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rtPreco)
                    .addComponent(cxPreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rtCereais)
                    .addComponent(cxCereais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btMalte)
                    .addComponent(rtCereais1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btCadastrar)
                    .addComponent(btLimpar))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rtCodAlt)
                    .addComponent(cxCodigoAlt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btAltCadastro1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rtCodDel)
                    .addComponent(cxCodigoDel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(btSair)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cxCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cxCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cxCodigoActionPerformed

    private void cxMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cxMarcaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cxMarcaActionPerformed

    private void cxOrigemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cxOrigemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cxOrigemActionPerformed

    private void cxTeorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cxTeorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cxTeorActionPerformed

    private void cxPrecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cxPrecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cxPrecoActionPerformed

    private void btCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCadastrarActionPerformed
        // TODO add your handling code here:
        cadastrarblend();
        listTabBlend();
    }//GEN-LAST:event_btCadastrarActionPerformed

    public void cadastrarblend(){
      blend = new Blended();
      try{
         blend.setCodigo(Integer.parseInt(cxCodigo.getText()));
         blend.setMarca(cxMarca.getText());
         blend.setOrigem(cxOrigem.getText());
        try{
            blend.getInfos().setTeor(Integer.parseInt(cxTeor.getText()));
            try{
                blend.getInfos().setPreco(Float.parseFloat(cxPreco.getText()));
                blend.setCereais(cxCereais.getText());
                if(btMalte.isSelected()){
                    blend.setMalte(true);
                } else{blend.setMalte(false);}
      
                blend = gerWhis.cadBlend(blend);
      
                if(blend != null){
                    JOptionPane.showMessageDialog(null,"Produto cadastrado com sucesso!", "Cadastro realizado", 1);
                    limpar();
                }else{
                    JOptionPane.showMessageDialog(null, "Produto nao cadastrado!\nCodigo ja validado por outro produto", "Erro de cadastro",1);
                    cxCodigo.setText("");
                    cxCodigo.requestFocus();
                }
            }catch(NumberFormatException nfe){
                JOptionPane.showMessageDialog(null, "O preco deve ser um valor inteiro", "Erro de formato de entrada", 0);
                cxPreco.setText("");
                cxPreco.requestFocus(); 
            }catch(NumberNegException nge){
                JOptionPane.showMessageDialog(null, "O preco deve ser um valor positivo", "Erro de formato de entrada", 0);
                cxPreco.setText("");
                cxPreco.requestFocus();
            }
            
        }catch(NumberFormatException nne){
            JOptionPane.showMessageDialog(null, "O teor alcoolico deve ser um valor inteiro", "Erro de formato de entrada", 0);
            cxTeor.setText("");
            cxTeor.requestFocus();
        }catch(PercentLimitException ple){
            JOptionPane.showMessageDialog(null, "O teor alcoolico deve ser menor que 100%", "Erro de formato de entrada", 0);
            cxTeor.setText("");
            cxTeor.requestFocus();
        }catch(NumberNegException nne){
            JOptionPane.showMessageDialog(null, "O teor alcoolico deve ser um valor positivo", "Erro de formato de entrada", 0);
            cxTeor.setText("");
            cxTeor.requestFocus();
        }
        
      } catch(NumberNegException nne){
          JOptionPane.showMessageDialog(null, "O codigo deve ser um valor positivo", "Erro de formato de entrada", 0);
          cxCodigo.setText("");
          cxCodigo.requestFocus();
      }catch (NumberFormatException nfe){
          JOptionPane.showMessageDialog(null, "O codigo deve ser um valor inteiro", "Erro de formato de entrada", 0);
          cxCodigo.setText("");
          cxCodigo.requestFocus();
      }
      
    }//end of cadastrar
    
    public void listTabBlend(){
        DefaultTableModel modelo = (DefaultTableModel) tblBlend.getModel();
        int posLin = 0;
        modelo.setRowCount(posLin);
        
        for(Blended blend : gerWhis.getBdBlend()){
            modelo.insertRow(posLin, new Object[]{blend.getCodigo(), blend.getMarca(), blend.getOrigem(), blend.getInfos().getTeor(), blend.getInfos().getPreco(), blend.getCereais(), blend.getMalte()});
            posLin++;
        }
    }
    
    private void btLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimparActionPerformed
        limpar();
    }//GEN-LAST:event_btLimparActionPerformed

    private void btSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSairActionPerformed
        // TODO add your handling code here:
        sair();
    }//GEN-LAST:event_btSairActionPerformed

    private void cxCereaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cxCereaisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cxCereaisActionPerformed

    private void btMalteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMalteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btMalteActionPerformed

    private void btAltCadastro1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAltCadastro1ActionPerformed
        // TODO add your handling code here:
        alterarPreco();
        listTabBlend();
        limpar();
    }//GEN-LAST:event_btAltCadastro1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        excluir();
        listTabBlend();
        limpar();
    }//GEN-LAST:event_jButton1ActionPerformed
    
    
    public void excluir(){
        blend = new Blended();
        try{
            blend.setCodigo(Integer.parseInt(cxCodigoDel.getText()));
            
            blend = gerWhis.consBlendCodigo(blend);
            
            if(blend != null){
                int x = JOptionPane.showConfirmDialog(null,"Deseja realmente excluir?","Confirmar exclusão de dado", JOptionPane.YES_NO_OPTION);
                if(x ==0){
                    blend = gerWhis.delBlend(blend);
                    JOptionPane.showMessageDialog(null,"Produto excluido com sucesso!","Exclusao de produto",1);
                    limpar();
                }
            }else{JOptionPane.showMessageDialog(null,"Produto nao encontrado", "Erro de busca", 0);}
        }catch(NumberFormatException nfe){
            JOptionPane.showMessageDialog(null,"O codigo deve ser um valor inteiro", "Erro de formato de entrada", 0);
            cxCodigoDel.setText("");
            cxCodigoDel.requestFocus();
        }catch(NumberNegException nne){
            JOptionPane.showMessageDialog(null,"O codigo deve ser um valor positivo","Erro de formato de entrada", 0);
            cxCodigoDel.setText("");
            cxCodigoDel.requestFocus();
        }
    }
    
    public void alterarPreco(){
        blend = new Blended();
        try{
            blend.setCodigo(Integer.parseInt(cxCodigoAlt.getText()));
            
            blend = gerWhis.consBlendCodigo(blend);
            
            if(blend != null){
                blend = gerWhis.altPrecoBlend(blend);
            }else{JOptionPane.showMessageDialog(null,"Produto nao encontrado", "Erro de busca", 0);}          
        }catch(NumberFormatException nfe){
            JOptionPane.showMessageDialog(null,"O codigo deve ser um valor inteiro", "Erro de formato de entrada", 0);
            cxCodigoAlt.setText("");
            cxCodigoAlt.requestFocus();
        }catch(NumberNegException nne){
            JOptionPane.showMessageDialog(null,"O codigo deve ser um valor positivo","Erro de formato de entrada", 0);
            cxCodigoAlt.setText("");
            cxCodigoAlt.requestFocus();
        }
    }
    
    public void sair(){
        int resp = JOptionPane.showConfirmDialog(null, "Deseja sair do cadastro?", "Confirmacao de saida", JOptionPane.YES_NO_OPTION);
        if(resp == 0){
            this.dispose();    
        }
    }
    
    public void limpar(){
        cxCodigo.setText("");
        cxMarca.setText("");
        cxOrigem.setText("");
        cxTeor.setText("");
        cxPreco.setText("");
        cxCereais.setText("");
        btMalte.setSelected(false);
        cxCodigoAlt.setText("");
        cxCodigoDel.setText("");
        cxCodigo.requestFocus();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadBlended.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadBlended.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadBlended.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadBlended.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadBlended().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAltCadastro1;
    private javax.swing.JButton btCadastrar;
    private javax.swing.JButton btLimpar;
    private javax.swing.JRadioButton btMalte;
    private javax.swing.JButton btSair;
    private javax.swing.JTextField cxCereais;
    private javax.swing.JTextField cxCodigo;
    private javax.swing.JTextField cxCodigoAlt;
    private javax.swing.JTextField cxCodigoDel;
    private javax.swing.JTextField cxMarca;
    private javax.swing.JTextField cxOrigem;
    private javax.swing.JTextField cxPreco;
    private javax.swing.JTextField cxTeor;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel rtCereais;
    private javax.swing.JLabel rtCereais1;
    private javax.swing.JLabel rtCodAlt;
    private javax.swing.JLabel rtCodDel;
    private javax.swing.JLabel rtCodigo;
    private javax.swing.JLabel rtMarca;
    private javax.swing.JLabel rtOrigem;
    private javax.swing.JLabel rtPreco;
    private javax.swing.JLabel rtTeor;
    private javax.swing.JLabel rtTitulo;
    private javax.swing.JTable tblBlend;
    // End of variables declaration//GEN-END:variables
}
