//Aluno: Claudiney Júnoior Givisiez Thomáz R.A.: 2266326

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author claud
 */
public class CadSingle extends javax.swing.JFrame {

    private Single single;
    private GerWhiskeys gerWhis = new GerWhiskeys();
    
    private static CadSingle cadSingleUnic;
    /**
     * Creates new form CadSingle
     */
    private CadSingle() {
        initComponents();
    }
    
    public static CadSingle getCadSingle(){
        if(cadSingleUnic == null){
            cadSingleUnic = new CadSingle();
        }
        return cadSingleUnic;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rtTitulo1 = new javax.swing.JLabel();
        rtCodigo = new javax.swing.JLabel();
        rtMarca = new javax.swing.JLabel();
        rtOrigem = new javax.swing.JLabel();
        rtTeor = new javax.swing.JLabel();
        rtPreco = new javax.swing.JLabel();
        rtPreco1 = new javax.swing.JLabel();
        rtPreco2 = new javax.swing.JLabel();
        cxCodigo = new javax.swing.JTextField();
        cxMarca = new javax.swing.JTextField();
        cxOrigem = new javax.swing.JTextField();
        cxTeor = new javax.swing.JTextField();
        cxPreco = new javax.swing.JTextField();
        cxGrao = new javax.swing.JTextField();
        btPremium = new javax.swing.JRadioButton();
        btCadastrar = new javax.swing.JButton();
        btLimpar = new javax.swing.JButton();
        btSair = new javax.swing.JButton();
        btAltCadastro = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSingle = new javax.swing.JTable();
        rtCodAlt = new javax.swing.JLabel();
        cxCodigoAlt = new javax.swing.JTextField();
        rtCodDel = new javax.swing.JLabel();
        cxCodigoDel = new javax.swing.JTextField();
        btExcluir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        rtTitulo1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        rtTitulo1.setText("Cadastrar Single");

        rtCodigo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        rtCodigo.setText("Codigo:");

        rtMarca.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        rtMarca.setText("Marca:");

        rtOrigem.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        rtOrigem.setText("Origem:");

        rtTeor.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        rtTeor.setText("Preco:");

        rtPreco.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        rtPreco.setText("Grao:");

        rtPreco1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        rtPreco1.setText("Teor:");

        rtPreco2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        rtPreco2.setText("Premium:");

        cxCodigo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cxCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cxCodigoActionPerformed(evt);
            }
        });

        cxMarca.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cxMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cxMarcaActionPerformed(evt);
            }
        });

        cxOrigem.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cxOrigem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cxOrigemActionPerformed(evt);
            }
        });

        cxTeor.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cxTeor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cxTeorActionPerformed(evt);
            }
        });

        cxPreco.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cxPreco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cxPrecoActionPerformed(evt);
            }
        });

        cxGrao.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cxGrao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cxGraoActionPerformed(evt);
            }
        });

        btPremium.setText("Single Premium");
        btPremium.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPremiumActionPerformed(evt);
            }
        });

        btCadastrar.setText("Cadastrar");
        btCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCadastrarActionPerformed(evt);
            }
        });

        btLimpar.setText("Limpar");
        btLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimparActionPerformed(evt);
            }
        });

        btSair.setText("Sair");
        btSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSairActionPerformed(evt);
            }
        });

        btAltCadastro.setText("Alterar Preco");
        btAltCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAltCadastroActionPerformed(evt);
            }
        });

        tblSingle.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Codigo", "Marca", "Origem", "Teor", "Preco", "Grao", "Premium"
            }
        ));
        jScrollPane1.setViewportView(tblSingle);

        rtCodAlt.setText("Codigo para alterar: ");

        cxCodigoAlt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cxCodigoAltActionPerformed(evt);
            }
        });

        rtCodDel.setText("Codigo para deletar:");

        btExcluir.setText("Excluir");
        btExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rtCodigo)
                                .addGap(121, 121, 121)
                                .addComponent(cxCodigo))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rtMarca)
                                .addGap(126, 126, 126)
                                .addComponent(cxMarca))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rtOrigem)
                                .addGap(116, 116, 116)
                                .addComponent(cxOrigem))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rtPreco1)
                                .addGap(141, 141, 141)
                                .addComponent(cxTeor))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rtTeor)
                                .addGap(130, 130, 130)
                                .addComponent(cxPreco))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rtPreco)
                                    .addComponent(rtPreco2))
                                .addGap(100, 100, 100)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btPremium)
                                    .addComponent(cxGrao, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(btCadastrar)
                                        .addGap(18, 18, 18)
                                        .addComponent(btLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addComponent(rtTitulo1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rtCodDel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cxCodigoDel))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(rtCodAlt)
                                .addGap(2, 2, 2)
                                .addComponent(cxCodigoAlt, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btAltCadastro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btExcluir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(80, 80, 80)
                        .addComponent(btSair, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rtTitulo1)
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rtCodigo)
                    .addComponent(cxCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rtMarca)
                    .addComponent(cxMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rtOrigem)
                    .addComponent(cxOrigem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rtPreco1)
                    .addComponent(cxTeor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rtTeor)
                    .addComponent(cxPreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rtPreco)
                    .addComponent(cxGrao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rtPreco2)
                    .addComponent(btPremium))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btLimpar)
                    .addComponent(btCadastrar))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rtCodAlt)
                    .addComponent(cxCodigoAlt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btAltCadastro))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btSair))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rtCodDel)
                            .addComponent(cxCodigoDel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btExcluir))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cxCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cxCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cxCodigoActionPerformed

    private void cxMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cxMarcaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cxMarcaActionPerformed

    private void cxOrigemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cxOrigemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cxOrigemActionPerformed

    private void cxTeorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cxTeorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cxTeorActionPerformed

    private void cxPrecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cxPrecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cxPrecoActionPerformed

    private void cxGraoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cxGraoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cxGraoActionPerformed

    private void btPremiumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPremiumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btPremiumActionPerformed

    private void btCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCadastrarActionPerformed
        // TODO add your handling code here:
        cadastrarSingle();
        listTabSingle();
    }//GEN-LAST:event_btCadastrarActionPerformed
    
    
    public void cadastrarSingle(){
        
        single = new Single();
        try{
            single.setCodigo(Integer.parseInt(cxCodigo.getText()));
            single.setMarca(cxMarca.getText());
            single.setOrigem(cxOrigem.getText());
            try{
                single.getInfos().setTeor(Integer.parseInt(cxTeor.getText()));
                try{
                    single.getInfos().setPreco(Float.parseFloat(cxPreco.getText()));
                    single.setCereal(cxGrao.getText());
                    if(btPremium.isSelected()){
                        single.setPremium(true);
                    } else{single.setPremium(false);}
        
                    single = gerWhis.cadSingle(single);
        
                    if(single != null){
                        JOptionPane.showMessageDialog(null,"Produto cadastrado com sucesso!", "Cadastro realizado", 1);
                        limpar();
                    }else{
                        JOptionPane.showMessageDialog(null, "Produto nao cadastrado\nCodigo ja validado por outro produto", "Erro de cadastro",1);
                        cxCodigo.setText("");
                        cxCodigo.requestFocus();
                }
                }catch(NumberFormatException nfe){
                    JOptionPane.showMessageDialog(null, "O preco deve ser um valor inteiro", "Erro de formato de entrada", 0);
                    cxPreco.setText("");
                    cxPreco.requestFocus();
                }catch(NumberNegException nge){
                    JOptionPane.showMessageDialog(null, "O preco deve ser um valor positivo", "Erro de formato de entrada", 0);
                    cxPreco.setText("");
                    cxPreco.requestFocus();
                }
            }catch(NumberFormatException nfe){
                JOptionPane.showMessageDialog(null,"O teor alcoolico deve ser um valor inteiro","Erro de formato de entrada", 0);
                cxTeor.setText("");
                cxTeor.requestFocus();
            }catch(NumberNegException nne){
                JOptionPane.showMessageDialog(null,"O teor alcoolico deve ser um valor positivo","Erro de formato de entrada", 0);
                cxTeor.setText("");
                cxTeor.requestFocus();
            }catch(PercentLimitException ple){
                JOptionPane.showMessageDialog(null,"O teor alcoolico deve ser um valor menor que 100%","Erro de formato de entrada", 0);
                cxTeor.setText("");
                cxTeor.requestFocus();     
            }
            
            
        }catch(NumberFormatException nfe){
            JOptionPane.showMessageDialog(null,"O codigo deve ser um valor inteiro", "Erro de formato de entrada", 0);
            cxCodigo.setText("");
            cxCodigo.requestFocus();
        }catch(NumberNegException nne){
            JOptionPane.showMessageDialog(null,"O codigo deve ser um valor positivo","Erro de formato de entrada", 0);
            cxCodigo.setText("");
            cxCodigo.requestFocus();
        }      
    }
    
    public void listTabSingle(){
        DefaultTableModel modelo = (DefaultTableModel) tblSingle.getModel();
        int posLin = 0;
        modelo.setRowCount(posLin);
        
        for(Single single : gerWhis.getBdSingle()){
            modelo.insertRow(posLin, new Object[]{single.getCodigo(), single.getMarca(), single.getOrigem(), single.getInfos().getTeor(), single.getInfos().getPreco(), single.getCereal(), single.getPremium()});
            posLin++;
        }
    }
    
    private void btLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimparActionPerformed
        limpar();
    }//GEN-LAST:event_btLimparActionPerformed

    private void btSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSairActionPerformed
        // TODO add your handling code here:
        sair();
    }//GEN-LAST:event_btSairActionPerformed

    private void btAltCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAltCadastroActionPerformed
        // TODO add your handling code here:
        alterarPreco();
        listTabSingle();
        limpar();
    }//GEN-LAST:event_btAltCadastroActionPerformed

    private void cxCodigoAltActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cxCodigoAltActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cxCodigoAltActionPerformed

    private void btExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcluirActionPerformed
        // TODO add your handling code here:
        excluir();
        listTabSingle();
        limpar();
    }//GEN-LAST:event_btExcluirActionPerformed
    
    public void excluir(){
        single = new Single();
        try{
            single.setCodigo(Integer.parseInt(cxCodigoDel.getText()));
            
            single = gerWhis.consSingleCodigo(single);
            
            if(single != null){
                int x = JOptionPane.showConfirmDialog(null,"Deseja realmente excluir?","Confirmar exclusão de dado", JOptionPane.YES_NO_OPTION);
                if(x ==0){
                    single = gerWhis.delSingle(single);
                    JOptionPane.showMessageDialog(null,"Produto excluido com sucesso!","Exclusao de produto",1);
                    limpar();
                }
            }else{JOptionPane.showMessageDialog(null,"Produto nao encontrado", "Erro de busca", 0);}
        }catch(NumberFormatException nfe){
            JOptionPane.showMessageDialog(null,"O codigo deve ser um valor inteiro", "Erro de formato de entrada", 0);
            cxCodigoDel.setText("");
            cxCodigoDel.requestFocus();
        }catch(NumberNegException nne){
            JOptionPane.showMessageDialog(null,"O codigo deve ser um valor positivo","Erro de formato de entrada", 0);
            cxCodigoDel.setText("");
            cxCodigoDel.requestFocus();
        }
    }
    
    
    public void alterarPreco(){
        single = new Single();
        try{
            single.setCodigo(Integer.parseInt(cxCodigoAlt.getText()));
            
            single = gerWhis.consSingleCodigo(single);
            
            if(single != null){
                single = gerWhis.altPrecoSingle(single);
            }else{JOptionPane.showMessageDialog(null,"Produto nao encontrado", "Erro de busca", 0);}
        }catch(NumberFormatException nfe){
            JOptionPane.showMessageDialog(null,"O codigo deve ser um valor inteiro", "Erro de formato de entrada", 0);
            cxCodigoAlt.setText("");
            cxCodigoAlt.requestFocus();
        }catch(NumberNegException nne){
            JOptionPane.showMessageDialog(null,"O codigo deve ser um valor positivo","Erro de formato de entrada", 0);
            cxCodigoAlt.setText("");
            cxCodigoAlt.requestFocus();
        }
    }
    
    public void sair(){
        int resp = JOptionPane.showConfirmDialog(null, "Deseja sair do cadastro?", "Confirmacao de saida", JOptionPane.YES_NO_OPTION);
        if(resp == 0){
            this.dispose(); 
        }
    }
    
    public void limpar(){
        cxCodigo.setText("");
        cxMarca.setText("");
        cxOrigem.setText("");
        cxTeor.setText("");
        cxPreco.setText("");
        cxGrao.setText("");
        btPremium.setSelected(false);
        cxCodigoAlt.setText("");
        cxCodigoDel.setText("");
        cxCodigo.requestFocus();
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadSingle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadSingle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadSingle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadSingle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadSingle().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAltCadastro;
    private javax.swing.JButton btCadastrar;
    private javax.swing.JButton btExcluir;
    private javax.swing.JButton btLimpar;
    private javax.swing.JRadioButton btPremium;
    private javax.swing.JButton btSair;
    private javax.swing.JTextField cxCodigo;
    private javax.swing.JTextField cxCodigoAlt;
    private javax.swing.JTextField cxCodigoDel;
    private javax.swing.JTextField cxGrao;
    private javax.swing.JTextField cxMarca;
    private javax.swing.JTextField cxOrigem;
    private javax.swing.JTextField cxPreco;
    private javax.swing.JTextField cxTeor;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel rtCodAlt;
    private javax.swing.JLabel rtCodDel;
    private javax.swing.JLabel rtCodigo;
    private javax.swing.JLabel rtMarca;
    private javax.swing.JLabel rtOrigem;
    private javax.swing.JLabel rtPreco;
    private javax.swing.JLabel rtPreco1;
    private javax.swing.JLabel rtPreco2;
    private javax.swing.JLabel rtTeor;
    private javax.swing.JLabel rtTitulo1;
    private javax.swing.JTable tblSingle;
    // End of variables declaration//GEN-END:variables
}
